copy /y "%XEngine_Library%\x64\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_Core\XEngine_OPenSsl.dll" "./"

copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\HelpComponents_DataBase.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\HelpComponents_Packets.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\HelpComponents_Authorize.dll" "./"

copy /y "%XEngine_Library%\x64\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_RfcComponents\RfcComponents_WSProtocol.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_RfcComponents\RfcComponents_EmailClient.dll" "./"

copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\bson-1.0.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\mongoc-1.0.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\libmariadb.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\libpq.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\sqlite3.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_HelpComponents\zlib1.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_LibEx\libcrypto-1_1.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_LibEx\libssl-1_1.dll" "./"
copy /y "%XEngine_Library%\x64\XEngine_LibEx\libcurl.dll" "./"