name: fedora build workflows

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
      - '.github/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    container:
      image: fedora:${{ matrix.fedora-version }}
      options: --platform ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            fedora-version: 42
            artifact: x86-64
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
            fedora-version: 41
            artifact: x86-64

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4

      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: sub module checkout (opensource)
        uses: actions/checkout@v4
        with:
          repository: libxengine/XEngine_OPenSource
          path: XEngine_Source/XEngine_Depend

      - name: install system package
        run: |
            dnf update -y
            dnf install gcc g++ make git jq unzip wget -y

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: install xengine library
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_Fedora_${{ matrix.fedora-version }}_${{ matrix.artifact }}.zip
            unzip ./XEngine_Fedora_${{ matrix.fedora-version }}_${{ matrix.artifact }}.zip -d ./XEngine_Fedora_${{ matrix.fedora-version }}_${{ matrix.artifact }}
            cd XEngine_Fedora_${{ matrix.fedora-version }}_${{ matrix.artifact }}
            
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
      - name: make
        run: |
            cd XEngine_Source
            make
            make FLAGS=InstallAll
            make FLAGS=CleanAll

            make RELEASE=1
            make FLAGS=InstallAll
            make FLAGS=CleanAll
            cd ..
      - name: test
        run: |
            cd XEngine_Release
            ./XEngine_ProxyServiceApp -t

      - name: Upload folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_ProxyServiceApp-Fedora_${{ matrix.fedora-version }}_${{ matrix.artifact }}
          path: XEngine_Release/
          retention-days: 1