name: macos build workflows

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
  
permissions:
  contents: read
  
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
        
       # 检出依赖的xengine仓库到指定的xengine目录
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine
          ref: 'master'

      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update

      - name: brew install
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            
      # 设置依赖库的环境变量
      - name: Set up Dependency Environment Variables
        run: |
            cd libxengine
            chmod 777 *
            ./XEngine_LINEnv.sh -i 3
            cd ..
      #编译
      - name: make debug
        run: | 
            cd XEngine_Source
            make PLATFORM=mac 
            make PLATFORM=mac FLAGS=InstallAll
            make PLATFORM=mac FLAGS=CleanAll
      - name: make release
        run: |
            cd XEngine_Source
            make PLATFORM=mac RELEASE=1
            make PLATFORM=mac FLAGS=InstallAll
            make PLATFORM=mac FLAGS=CleanAll
      - name: test
        run: |
            cd XEngine_Release
            ./XEngine_AuthorizeService -t

      - name: Upload folder as artifact with mac
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_AuthorizeService-x86_64-Mac
          path: XEngine_Release/