name: ubuntu build workflows

on:
  push:
    branches: 
      - 'develop'
    paths:
      - 'XEngine_Source/**'
      - 'XEngine_Release/**'
      - '.github/**'
  
jobs:
  build:
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-24.04
          - os: ubuntu-22.04-arm
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
        
      - name: Checkout dependency repository (xengine)
        uses: actions/checkout@v4
        with:
          repository: libxengine/libxengine
          path: libxengine

      - name: sub module checkout (opensource)
        run: |
            git submodule init
            git submodule update

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
        
      - name: Set up Dependency ubuntu24.04 Environment
        if: matrix.os == 'ubuntu-24.04'
        run: |
            cd libxengine
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
      - name: Set up Dependency ubuntu24.04 ARM64 Environment
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_24.04_Arm64.zip
            unzip ./XEngine_UBuntu_24.04_Arm64.zip -d ./XEngine_UBuntu_24.04_Arm64
            cd XEngine_UBuntu_24.04_Arm64
            
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
      - name: Set up Dependency ubuntu22.04 Environment
        if: matrix.os == 'ubuntu-22.04'
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_22.04_x86-64.zip
            unzip ./XEngine_UBuntu_22.04_x86-64.zip -d ./XEngine_UBuntu_22.04_x86-64
            cd XEngine_UBuntu_22.04_x86-64
            
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
      - name: Set up Dependency ubuntu22.04 arm64 Environment
        if: matrix.os == 'ubuntu-22.04-arm'
        run: |
            latest_tag=$(curl -s https://api.github.com/repos/libxengine/libxengine/releases/latest | jq -r .tag_name)
            wget https://github.com/libxengine/libxengine/releases/download/$latest_tag/XEngine_UBuntu_22.04_Arm64.zip
            unzip ./XEngine_UBuntu_22.04_Arm64.zip -d ./XEngine_UBuntu_22.04_Arm64
            cd XEngine_UBuntu_22.04_Arm64
            
            chmod 777 *
            sudo ./XEngine_LINEnv.sh -i 3
            
      - name: make x86
        if: matrix.os == 'ubuntu-24.04' || matrix.os == 'ubuntu-22.04'
        run: | 
            cd XEngine_Source
            make RELEASE=1
            make FLAGS=InstallAll
            make FLAGS=CleanAll
            cd ..
      - name: make arm
        if: matrix.os == 'ubuntu-24.04-arm' || matrix.os == 'ubuntu-22.04-arm'
        run: | 
            cd XEngine_Source
            make ARCH=Arm64 RELEASE=1
            make FLAGS=InstallAll
            make FLAGS=CleanAll
            cd ..
      - name: test
        run: |
            cd XEngine_Release
            ./XEngine_AuthorizeService -t

      - name: Upload folder as artifact with ubuntu22.04
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_AuthorizeService-Ubuntu_22.04_x86-64
          path: XEngine_Release/
          retention-days: 1
      - name: Upload folder as artifact with ubuntu24.04
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_AuthorizeService-Ubuntu_24.04_x86-64
          path: XEngine_Release/
          retention-days: 1
      - name: Upload folder as artifact with ubuntu24.04 arm64
        if: matrix.os == 'ubuntu-24.04-arm'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_AuthorizeService-Ubuntu_24.04_Arm64
          path: XEngine_Release/
          retention-days: 1
      - name: Upload folder as artifact with ubuntu22.04 arm64
        if: matrix.os == 'ubuntu-22.04-arm'
        uses: actions/upload-artifact@v4
        with:
          name: XEngine_AuthorizeService-Ubuntu_22.04_Arm64
          path: XEngine_Release/
          retention-days: 1